version: "3.8"
services:
  clamav:
    image: clamav/clamav:latest
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - clamav:/var/lib/clamav
    ports:
      - "3310:3310"
volumes:
  clamav:
    external: true
